config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
  	authenticated :user do
   	 root 'meetings#index', as: :authenticated_root
  	end

  	unauthenticated do
    	root 'devise/sessions#new', as: :unauthenticated_root
  	end
  end

  get "meetings" => "meetings#index"
  get "meetings/new" => "meetings#new"
  post "meetings" => "meetings#create"
  get "meetings/:id" => "meetings#moreinfo", as: "meeting"
  get "meetings/:id/edit" => "meetings#edit", as: "meeting_edit"
  patch "meetings/:id" => "meetings#update"
  delete "meetings/:id" => "meetings#delete"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	
	validates :name, :date, :start_time, :end_time, :user_id, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :meetings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@meeting = Meeting.all
	end

	def new
		@meeting = current_user.meetings.build
	end

	def create
		meeting = current_user.meetings.build(meeting_params)
		if meeting.save
			redirect_to meetings_path
		else 
			flash[:errors] = meeting.errors.full_messages
			redirect_back(fallback_location:"/")
		end
	end

	def moreinfo
		@meeting = Meeting.find(params[:id])
	end

	def edit
		@meeting = Meeting.find(params[:id])
	end

	def update
		meeting = Meeting.find(params[:id])
		if meeting.update(meeting_params)
			redirect_to meetings_path
		else 
			flash[:errors] = meeting.errors.full_messages
			redirect_back(fallback_location:"/")
		end
	end

	def delete 
		meeting = Meeting.find(params[:id])
		meeting.destroy
		redirect_to meetings_path
	end


private 
	def meeting_params
	 	params.require(:meeting).permit(:name, :date, :start_time, :end_time, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class:"alert alert-info") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>

<%= form_for(@meeting) do |f| %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %><br/>
	</p>
	<p>
		<%= f.label :date %><br/>
		<%= f.text_field :date %><br/>
	</p>
	<p>
		<%= f.label :start_time %><br/>
		<%= f.text_field :start_time %><br/>
	</p>
	<p>
		<%= f.label :end_time %><br/>
		<%= f.text_field :end_time %><br/>
	</p>
	<p>
		<%= f.label :description %><br/>
		<%= f.text_field :description %><br/>
	</p>
	<div id="button">
		<%= f.submit %>
	</div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Edit <%= @meeting.name %></h1>

<%= render partial: "meetings/form" %>

<div id="options">
	<%= link_to "Back", meetings_path %>
</div>

app/views/meetings/index.html.erb
<div>
	<h1>Listing <%= pluralize(@meeting.size, "Event") %></h1>
</div>

<table>
	<thead>
		<tr>
			<td>Name</td>
			<td>Date</td>
			<td>Start Time</td>
			<td>End Time</td>
		</tr>
	</thead>

	<tbody>
		<% @meeting.each do |meeting| %>
		<tr>
			<td> <%= meeting.name %> </td>
			<td> <%= meeting.date %> </td>
			<td> <%= meeting.start_time %> </td>
			<td> <%= meeting.end_time %> </td>
			<td>
				<%= link_to "More Info", meeting_path(meeting.id) %> |
				<%= link_to "Edit Info", meeting_edit_path(meeting.id) %> |
				<%= link_to "Delete Event", meeting_path(meeting.id), data: {method: :delete, confirm: "Are you sure?"} %>
			</td>
		</tr>
		<% end %>
	</tbody>
	
</table>

<div id="options">
	<%= link_to "New Event", meetings_new_path %> |
	<%= link_to "Log Out", destroy_user_session_path, method: :delete%>
</div>

app/views/meetings/moreinfo.html.erb
<h1>More info on <%= @meeting.name %> </h1>

<div>
	<table>
		<thead>
			<tr>
				<td>Name</td>
				<td>Start Time</td>
				<td>End Time</td>
				<td>Description</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%=@meeting.name %></td>
				<td><%=@meeting.start_time %></td>
				<td><%=@meeting.end_time %></td>
				<td><%=@meeting.description %></td>
			</tr>
		</tbody>
	</table>
</div>

<div id="options">
	<%= link_to "Back", meetings_path %>
</div>

app/views/meetings/new.html.erb
<h1>Create a New Event</h1>

<%= render partial: "meetings/form" %>

<div id="options">
	<%= link_to "Back", meetings_path %> 
</div>